<?php
/**
 * Created by PhpStorm.
 * User: j-zhanghongmin
 * Date: 2016/10/27
 * Time: 16:46
 */
namespace app\controllers;
use yii\web\Controller;
use app\components\HelloWorldAction;
use yii\filters\VerbFilter;
use Yii;
use \yii\web\NotFoundHttpException;


class IndexController extends Controller
{
    const EVENT_HELLO = 'hello';
    private $age = 18;
//    public function behaviors()
//    {
//        return [
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'delete' => ['POST'],
//                ],
//            ],
//        ];
//    }

//    public $defaultAction = 'zhm';
//    public function actions()
//    {
//        return [
//            'page' => [
//                'class' => 'yii\web\ViewAction',
//            ],
//        ];
//    }
public function beforeAction($action)
{
    $this->enableCsrfValidation = false;
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
}

    public function actionIndex()
    {

//        \Yii::$app->response->redirect('http://www.btime.com/', 301)->send();
//        echo 'test';
//        $action = new HelloWorldAction();
//      $res =  \Yii::$app->helloWorld->run();
//     echo $res;
//        \yii::$app->session->set('name','zhm111');
//        \yii::$app->session->set('age','18111');
//        $name = \yii::$app->session->get('name', 'default');
//        echo $name;
        // 请求 #1
//        $session = \yii::$app->session;
// 设置一个名为"postDeleted" flash 信息
//        $session->setFlash('postDeleted', 'You have successfully deleted your post.');

// 请求 #2
// 显示名为"postDeleted" flash 信息
//        echo $session->getFlash('postDeleted');

// 请求 #3
// $result 为 false，因为flash信息已被自动删除

//        throw new NotFoundHttpException('mei zhao dao');
//

//        echo $_SERVER['SCRIPT_FILENAME'];
//        $requset = Yii::$app->request;
//        $params = $requset->get();

//        $params = $requset->post('id');
//        var_dump($params);

//        $headers = Yii::$app->request->headers;
//        $accept = $headers->get('accept');
//        var_dump($accept);

//        $userHost = Yii::$app->request->userHost;
//        $userIp = Yii::$app->request->userIP;
//        var_dump($userHost,$userIp);

//        $response = Yii::$app->response;
//        $response->format = \yii\web\Response::FORMAT_JSON;
//        $response->data = ['message' => 'hello world'];

//        return \Yii::createObject([
//            'class' => 'yii\web\Response',
//            'format' => \yii\web\Response::FORMAT_JSON,
//            'data' => [
//                'message' => 'hello world',
//                'code' => 100,
//            ],
//        ]);

//        Yii::$app->response->redirect("http://www.baidu.com", 301);
//        \Yii::$app->response->redirect('http://example.com/new', 301)->send();

//        $sessions = Yii::$app->session;
//        if($sessions->isActive){
//            echo 'session is opening';
//            exit;
//        }else{
//            echo 'session is closed';
//            exit;
//        }
//        $sessions->set('name', 'zhm');
//        $name = $sessions->get('name');
//        echo $name;
//        $session['captcha']['number'] = 5;
//        $session['captcha']['lifetime'] = 3600;

//        $session['captcha'] = [
//            'number' => 5,
//            'lifetime' => 3600,
//        ];
//        $session['captcha.lifetime'] = 31600;
//        echo $session['captcha.lifetime'];


//        $cookies = Yii::$app->response->cookies;
//        $cookies->add(new \yii\web\Cookie([
//            'name' => 'language',
//            'value' => 'zh-CN',
//        ]));
//        Yii::$app->response->send();
//        $cookies->remove('language');

//        if(true){
//            throw new NotFoundHttpException('没找到');
//        }
//        \Yii::beginProfile('myBenchmark');
//
//  Yii::trace('start calculating average revenue', __METHOD__);
//\Yii::endProfile('myBenchmark');

//        echo 'etstdsd';
//
//        echo '@foo';
        echo Yii::getAlias('@web');
    }

    /**
     * @return int
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * @param int $age
     */
    public function setAge($age)
    {
        $this->age = $age;
    }

    public function actionZhm()
    {
//        $session = \yii::$app->session;
//        $result = $session->hasFlash('postDeleted');
//        $result = $session->has('name');
//        var_dump($result);
//        \yii::$app->co
//        echo 'test';
//        return $this->redirect('www.baidu.com', 301);
//     return  $this->render('zhm',[
//         'test' => '1111111'
//     ]);
//        \Yii::$app->response->redirect('http://example.com/new', 301)->send();
        \Yii::beginProfile('myBenchmark');
//       $cookies = \yii::$app->response->cookies;
        echo 'zhm';
        \Yii::endProfile('myBenchmark');
//        $cookies->add(new \yii\web\Cookie([
//            'name' => 'language',
//            'value' => 'zh-CN'
//        ]));
//        \
        Yii::trace('start calculating average revenue');


    }


}