<?php
/**
 * Created by PhpStorm.
 * User: j-zhanghongmin
 * Date: 2016/10/26
 * Time: 20:38
 */

namespace app\models;

use Yii;
use yii\base\Model;

class EntryForm extends Model
{
    public function fields()
    {
        return [
            // 字段名为 "email"，对应属性名为 "email_address"
            'email_address' => 'email',

        ];
    }
    //字段名
    public $name;
    public $email;

    public function rules()
    {
        return $rules = [
            [['name','email'], 'required'],
            ['email', 'email']
        ];
    }


    public function attributeLabels()
    {
        return [
            'name' => '姓名',
            'email' => '邮箱'
        ]; // TODO: Change the autogenerated stub
    }


}