<?php
/**
 * Created by PhpStorm.
 * User: j-zhanghongmin
 * Date: 2016/11/15
 * Time: 18:22
 */
namespace app\models;
use yii\base\Behavior;
use app\models\Personal;

// Step 2: 定义一个行为类，他将绑定到MyClass上
class MyBehavior extends Behavior
{
    public $prop1 = 'aaa';

    private $_prop2 = 'bbb';
    private $_prop3 = 'ccc';
    private $_prop4 = 'ddd';

    public function getProp2()
    {
        return $this->_prop2;
    }

    public function setProp3($value)
    {
        $this->_prop3 = $value;
    }

    public function foo()
    {
        echo 'foo';
        // ...
    }

    protected function bar()
    {
        echo 'bar';
        // ...
    }
    // 行为的一个属性
    public $property1 = 'This is property in MyBehavior.';

    // 行为的一个方法
    public function method1()
    {
       echo  'Method in MyBehavior is called1111111.';
    }

    public function events()
    {
        return [
            Personal::EVENT_HELLO => 'method1'
        ];
//        return parent::events(); // TODO: Change the autogenerated stub
    }
}